[package]
name = "gunter-app"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "gunter"
path = "src/main.rs"

[dependencies]
gunter-core = { path = "../gunter-core" }
gunter-term = { path = "../gunter-term" }
gunter-renderer = { path = "../gunter-renderer" }
portable-pty = { workspace = true }
vte = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
env_logger = { workspace = true }
arboard = { workspace = true }
